name = "MCLightTransport"
uuid = "b82e34d3-41f5-43e4-ae67-09331cb14329"
authors = ["bradeneliason <braden.eliason@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
